name: kpi_s_fct
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_secure_storage: ^9.2.4
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/food_logo.png

dependency_overrides:
  google_sign_in_web: null
