// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7_5fBVglK0W-Ou23_RL70NedlVkHW78',
    appId: '1:109599746267:web:3918a3147fc2c740e644fe',
    messagingSenderId: '109599746267',
    projectId: 'fir-kpi-9f606',
    authDomain: 'fir-kpi-9f606.firebaseapp.com',
    databaseURL: 'https://fir-kpi-9f606-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kpi-9f606.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQoJUGvtzhbpFF0nuBuso9VrVvFCpKco',
    appId: '1:109599746267:android:43991b19e32582fee644fe',
    messagingSenderId: '109599746267',
    projectId: 'fir-kpi-9f606',
    databaseURL: 'https://fir-kpi-9f606-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kpi-9f606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1dT7ysF1ss5J5JUK24I5_V5RLtUWKnFk',
    appId: '1:109599746267:ios:352b4a0d49bffd4ae644fe',
    messagingSenderId: '109599746267',
    projectId: 'fir-kpi-9f606',
    databaseURL: 'https://fir-kpi-9f606-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kpi-9f606.firebasestorage.app',
    iosBundleId: 'com.example.kpiPoject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1dT7ysF1ss5J5JUK24I5_V5RLtUWKnFk',
    appId: '1:109599746267:ios:352b4a0d49bffd4ae644fe',
    messagingSenderId: '109599746267',
    projectId: 'fir-kpi-9f606',
    databaseURL: 'https://fir-kpi-9f606-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kpi-9f606.firebasestorage.app',
    iosBundleId: 'com.example.kpiPoject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi7_5fBVglK0W-Ou23_RL70NedlVkHW78',
    appId: '1:109599746267:web:b4025d61a8d494a7e644fe',
    messagingSenderId: '109599746267',
    projectId: 'fir-kpi-9f606',
    authDomain: 'fir-kpi-9f606.firebaseapp.com',
    databaseURL: 'https://fir-kpi-9f606-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kpi-9f606.firebasestorage.app',
  );
}
